<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">

https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

url = sqlalchemy.URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="ebrasil",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

print("connecting with engine " + str(engine)) 

with engine.connect() as connection:
    print(connection.execute(sqlalchemy.text("SELECT current_database(), current_user")).fetchone())

connecting with engine Engine(postgresql+psycopg2://formation:***@postgres-source:5432/ebrasil)
('ebrasil', 'formation')

## Changement de répertoire

In [2]:
os.chdir("/opt/spark/data/ebrasil")

# DataFrame $products$

In [3]:
products = pd.read_csv('olist_products_dataset.csv')
products_translated = pd.read_csv('product_category_name_translation.csv')
cat = pd.merge(products, products_translated, on="product_category_name", how='left')
# cat = cat.drop(columns="product_category_name")

In [4]:
products.shape,cat.shape

((32951, 9), (32951, 10))

In [5]:
cat.isna().sum()

product_id                         0
product_category_name            610
product_name_lenght              610
product_description_lenght       610
product_photos_qty               610
product_weight_g                   2
product_length_cm                  2
product_height_cm                  2
product_width_cm                   2
product_category_name_english    623
dtype: int64

In [6]:
donnees = pd.read_csv('olist_products_dataset.csv')
donnees.rename(columns={col:col.replace('product_','') for col in donnees.columns[1:]},inplace=True)

In [7]:
donnees.head()

,product_id,category_name,name_lenght,description_lenght,photos_qty,weight_g,length_cm,height_cm,width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [8]:
categories = pd.read_csv('product_category_name_translation.csv')
categories.rename(columns={col:col.replace('product_','') for col in categories.columns},inplace=True)
categories.head()

            category_name  category_name_english
0            beleza_saude          health_beauty
1  informatica_acessorios  computers_accessories
2              automotivo                   auto
3         cama_mesa_banho         bed_bath_table
4        moveis_decoracao        furniture_decor

In [9]:
donnees = donnees.merge(categories,how='left',on='category_name')

In [10]:
donnees[donnees.category_name_english.isna()][['category_name',
                                               'category_name_english']].drop_duplicates()

                                      category_name category_name_english
105                                             NaN                   NaN
1628                                       pc_gamer                   NaN
5821  portateis_cozinha_e_preparadores_de_alimentos                   NaN

'kitchenware_tools_and_gadget'

In [11]:
donnees.loc[donnees.category_name_english.isna() & 
                    (donnees.category_name == 'pc_gamer'),'category_name_english'] = 'pc_gamer'
donnees.category_name_english[donnees.category_name_english.isna() & 
                    (donnees.category_name == 'portateis_cozinha_e_preparadores_de_alimentos') ] = 'kitchenware_tools_and_gadget'

In [12]:
donnees.category_name_english.fillna('not documented',inplace=True)

In [13]:
donnees.drop(columns='category_name',inplace=True)
donnees.rename(columns={'category_name_english':'category_name'},inplace=True)

In [14]:
donnees.head()

,product_id,name_lenght,description_lenght,photos_qty,weight_g,length_cm,height_cm,width_cm,category_name
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [15]:
donnees.isna().sum()

product_id              0
name_lenght           610
description_lenght    610
photos_qty            610
weight_g                2
length_cm               2
height_cm               2
width_cm                2
category_name           0
dtype: int64

## Sauvegarde en parquet

In [16]:
os.chdir("/opt/spark/notebooks/ecommerce")

In [17]:
donnees.to_parquet('products.parquet',compression='gzip', engine='pyarrow')

In [18]:
donnees.shape

(32951, 9)

In [19]:
!ls -al

total 34372
drwxr-xr-x 1 spark spark     512 Sep 24 16:33 .
drwxrwxrwx 1 root  root      512 Sep 24 15:55 ..
-rw-r--r-- 1 spark spark 4508308 Sep 24 16:33 customers.parquet
-rw-r--r-- 1 spark spark 4773153 Sep 24 16:33 items.parquet
-rw-r--r-- 1 spark spark 9489433 Sep 24 16:33 orders.parquet
-rw-r--r-- 1 spark spark 2466806 Sep 24 16:33 paymentsI.parquet
-rw-r--r-- 1 spark spark 2648930 Sep 24 16:33 payments.parquet
-rw-r--r-- 1 spark spark  958461 Sep 24 16:33 products.parquet
-rw-r--r-- 1 spark spark 7490087 Sep 24 16:33 reviews.parquet
-rw-r--r-- 1 spark spark 2847395 Sep 24 16:33 reviews_p.parquet

## Sauvegarde dans la base de données

In [20]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          32951 non-null  object
 1   name_lenght         32341 non-null  float64
 2   description_lenght  32341 non-null  float64
 3   photos_qty          32341 non-null  float64
 4   weight_g            32949 non-null  float64
 5   length_cm           32949 non-null  float64
 6   height_cm           32949 non-null  float64
 7   width_cm            32949 non-null  float64
 8   category_name       32951 non-null  object
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [21]:
with engine.connect() as connection:
    donnees.to_sql('products',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                        "product_id"         :sqlalchemy.types.String(80),
                        "name_lenght"        :sqlalchemy.types.Float(),
                        "description_lenght" :sqlalchemy.types.Float(),
                        "photos_qty"         :sqlalchemy.types.Float(),
                        "weight_g"           :sqlalchemy.types.Float(),
                        "length_cm"          :sqlalchemy.types.Float(),
                        "height_cm"          :sqlalchemy.types.Float(),
                        "width_cm"           :sqlalchemy.types.Float(),
                        "category_name"      :sqlalchemy.types.String(80)
               })

In [22]:
with engine.connect() as connection:
    requete  = "select count(*) from products"
    print(pd.read_sql_query(requete, connection))

   count
0  32951