<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">


https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

url = sqlalchemy.URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="ebrasil",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

print("connecting with engine " + str(engine)) 

with engine.connect() as connection:
    print(connection.execute(sqlalchemy.text("SELECT current_database(), current_user")).fetchone())

connecting with engine Engine(postgresql+psycopg2://formation:***@postgres-source:5432/ebrasil)
('ebrasil', 'formation')

## Changement de répertoire

In [2]:
os.chdir("/opt/spark/data/ebrasil")

# DataFrame $items$

In [3]:
donnees = pd.read_csv(os.path.join('olist_order_items_dataset.csv'))
donnees = donnees.merge(pd.read_parquet('/opt/spark/notebooks/ecommerce/orders.parquet')[['order_id', 'purchase_timestamp']],on='order_id')

In [4]:
donnees.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,purchase_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,2017-09-13 08:59:02
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,2017-04-26 10:53:06
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,2018-01-14 14:33:31
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,2018-08-08 10:00:35
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,2017-02-04 13:57:51

In [5]:
donnees.dtypes

order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date            object
price                         float64
freight_value                 float64
purchase_timestamp     datetime64[ns]
dtype: object

## Conversions des dates

In [6]:
donnees['shipping_limit']= pd.to_datetime(donnees.shipping_limit_date, format='%Y-%m-%d %H:%M:%S',errors='ignore')
donnees['limit']         = (donnees.shipping_limit - donnees.purchase_timestamp).dt.seconds/60/60

In [7]:
donnees.drop(columns=['shipping_limit_date','purchase_timestamp'],inplace=True)

In [8]:
donnees.dtypes

order_id                  object
order_item_id              int64
product_id                object
seller_id                 object
price                    float64
freight_value            float64
shipping_limit    datetime64[ns]
limit                    float64
dtype: object

In [9]:
donnees.isna().sum()

order_id          0
order_item_id     0
product_id        0
seller_id         0
price             0
freight_value     0
shipping_limit    0
limit             0
dtype: int64

In [10]:
donnees.order_id.nunique(),donnees.shape

(98666, (112650, 8))

In [11]:
donnees.groupby(['order_id','product_id']).agg('count').shape

(102425, 6)

In [12]:
donnees.groupby(['order_id','product_id','seller_id']).agg('count').shape

(102425, 5)

In [13]:
donnees.groupby(['order_id','order_item_id','product_id','seller_id']).agg('count').shape,donnees.shape

((112650, 4), (112650, 8))

In [14]:
donnees.head()

,order_id,order_item_id,product_id,seller_id,price,freight_value,shipping_limit,limit
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29,2017-09-19 09:45:35,0.775833
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93,2017-05-03 11:05:13,0.201944
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87,2018-01-18 14:48:30,0.249722
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79,2018-08-15 10:10:18,0.161944
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14,2017-02-13 13:57:51,0.000000

## Sauvegarde dans la base de données

In [15]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        112650 non-null  object
 1   order_item_id   112650 non-null  int64
 2   product_id      112650 non-null  object
 3   seller_id       112650 non-null  object
 4   price           112650 non-null  float64
 5   freight_value   112650 non-null  float64
 6   shipping_limit  112650 non-null  datetime64[ns]
 7   limit           112650 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 6.9+ MB

In [16]:
with engine.connect() as connection:
    donnees.to_sql('items',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                       "order_id"       :sqlalchemy.types.String(80),     
                       "order_item_id"  :sqlalchemy.types.Integer(),    
                       "product_id"     :sqlalchemy.types.String(80),
                       "seller_id"      :sqlalchemy.types.String(80),  
                       "price"          :sqlalchemy.types.Float(),
                       "freight_value"  :sqlalchemy.types.Float(),
                       "shipping_limit" :sqlalchemy.types.DateTime(),
                       "limit"          :sqlalchemy.types.Float()
               })

In [17]:
with engine.connect() as connection:
    requete  = "select count(*) from items"
    print(pd.read_sql_query(requete, connection))

    count
0  112650