<img src="https://raw.githubusercontent.com/rbizoi/PythonFormation/main/images/e-brasil.png" width="850">


https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce

# Les imports et initialisations des variables

In [1]:
from datetime import datetime
import pandas as pd, numpy as np, os, warnings, seaborn as sns, pickle, re, unicodedata
from datetime import datetime as dt
import sqlalchemy

warnings.filterwarnings(action="ignore")

url = sqlalchemy.URL.create(
    drivername="postgresql+psycopg2",
    username="formation",
    password="formation",
    host="postgres-source",
    port=5432,
    database="ebrasil",
)

engine = sqlalchemy.create_engine( 
    url, #url = "postgresql://formation:formation@postgres-source:5432/formation"
    pool_pre_ping=True,
)

print("connecting with engine " + str(engine)) 

with engine.connect() as connection:
    print(connection.execute(sqlalchemy.text("SELECT current_database(), current_user")).fetchone())

connecting with engine Engine(postgresql+psycopg2://formation:***@postgres-source:5432/ebrasil)
('ebrasil', 'formation')

In [2]:
!dir ..\donnees\ebrasil

dir: cannot access '..donneesebrasil': No such file or directory

## Changement de répertoire

In [3]:
os.chdir("/opt/spark/data/ebrasil")

# DataFrame $payments$

In [4]:
donnees = pd.read_csv('olist_order_payments_dataset.csv')
donnees.rename(columns={col:col.replace('payment_','') for col in donnees.columns[1:]},inplace=True)
donnees.sort_values(['order_id','sequential']).head(10)

,order_id,sequential,type,installments,value
85283,00010242fe8c5a6d1ba2dd792cb16214,1,credit_card,2,72.19
2499,00018f77f2f0320c557190d7a144bdd3,1,credit_card,3,259.83
12393,000229ec398224ef6ca0657da4fc703e,1,credit_card,5,216.87
32971,00024acbcdf0a6daa1e931b038114c75,1,credit_card,2,25.78
98711,00042b26cf59d7ce69dfabb4e55b4fd9,1,credit_card,3,218.04
50570,00048cc3ae777c65dbb7d2a0634bc1ea,1,boleto,1,34.59
35027,00054e8431b9d7675808bcb819fb4a32,1,credit_card,1,31.75
22082,000576fe39319847cbb9d288c5617fa6,1,credit_card,10,880.75
100792,0005a1a1728c9d785b8e2b08b904576c,1,credit_card,3,157.60
63353,0005f50442cb953dcd1d21e1fb923495,1,credit_card,1,65.39

In [5]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      103886 non-null  object
 1   sequential    103886 non-null  int64
 2   type          103886 non-null  object
 3   installments  103886 non-null  int64
 4   value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [6]:
payments = donnees.pivot_table( index='order_id',columns='type',
                     values=['installments','value'],
                     fill_value=0, dropna=False)
payments.columns = [col[0].replace('installments','int')+'_'+col[1] for col in payments.columns]
payments[['int_boleto',
          'int_credit_card',
          'int_debit_card',
          'int_not_defined',
          'int_voucher']]  = payments[['int_boleto',
                                       'int_credit_card',
                                       'int_debit_card',
                                       'int_not_defined',
                                       'int_voucher']].astype('int8')

In [7]:
payments['value'] = payments.value_boleto+\
                   payments.value_credit_card+\
                   payments.value_debit_card+\
                   payments.value_not_defined+\
                   payments.value_voucher

In [8]:
payments.head()

,int_boleto,int_credit_card,int_debit_card,int_not_defined,int_voucher,value_boleto,value_credit_card,value_debit_card,value_not_defined,value_voucher,value
order_id,,,,,,,,,,,
00010242fe8c5a6d1ba2dd792cb16214,0,2,0,0,0,0.0,72.19,0.0,0.0,0.0,72.19
00018f77f2f0320c557190d7a144bdd3,0,3,0,0,0,0.0,259.83,0.0,0.0,0.0,259.83
000229ec398224ef6ca0657da4fc703e,0,5,0,0,0,0.0,216.87,0.0,0.0,0.0,216.87
00024acbcdf0a6daa1e931b038114c75,0,2,0,0,0,0.0,25.78,0.0,0.0,0.0,25.78
00042b26cf59d7ce69dfabb4e55b4fd9,0,3,0,0,0,0.0,218.04,0.0,0.0,0.0,218.04

In [9]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99440 entries, 00010242fe8c5a6d1ba2dd792cb16214 to fffe41c64501cc87c801fd61db3f6244
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   int_boleto         99440 non-null  int8
 1   int_credit_card    99440 non-null  int8
 2   int_debit_card     99440 non-null  int8
 3   int_not_defined    99440 non-null  int8
 4   int_voucher        99440 non-null  int8
 5   value_boleto       99440 non-null  float64
 6   value_credit_card  99440 non-null  float64
 7   value_debit_card   99440 non-null  float64
 8   value_not_defined  99440 non-null  float64
 9   value_voucher      99440 non-null  float64
 10  value              99440 non-null  float64
dtypes: float64(6), int8(5)
memory usage: 5.8+ MB

## Sauvegarde dans la base de données

In [10]:
donnees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      103886 non-null  object
 1   sequential    103886 non-null  int64
 2   type          103886 non-null  object
 3   installments  103886 non-null  int64
 4   value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [11]:
with engine.connect() as connection:
    donnees.to_sql('payments',
               con=connection,
               if_exists='replace',
               index=False,
               dtype={ 
                       "order_id"       :sqlalchemy.types.String(80),     
                       "sequential"     :sqlalchemy.types.Integer(),    
                       "type"           :sqlalchemy.types.String(80),
                       "installments"   :sqlalchemy.types.Integer(),   
                       "value"          :sqlalchemy.types.Float()
               })

In [12]:
with engine.connect() as connection:
    requete  = "select count(*) from payments"
    print(pd.read_sql_query(requete, connection))

    count
0  103886